# Generated by Django 5.2.7 on 2026-01-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_pista_id_alter_reserva_id_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pista',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='Pega aquí el enlace de una foto de una pista de pádel', max_length=500, null=True),
        ),
    ]
