# Generated by Django 6.0.1 on 2026-05-03 13:06

from django.db import migrations, models


def inicializar_creditos_restantes(apps, schema_editor):
    Bono = apps.get_model('reservas', 'Bono')
    Usuario = apps.get_model('reservas', 'Usuario')

    for bono in Bono.objects.all():
        bono.creditos_restantes = bono.creditos
        bono.save(update_fields=['creditos_restantes'])

    for usuario in Usuario.objects.filter(creditos__gt=0):
        if not Bono.objects.filter(usuario=usuario).exists():
            Bono.objects.create(
                usuario=usuario,
                nombre='Saldo inicial',
                creditos=usuario.creditos,
                creditos_restantes=usuario.creditos,
                precio=0,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_pista_id_alter_reserva_id_alter_usuario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bono',
            name='creditos_restantes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(inicializar_creditos_restantes, migrations.RunPython.noop),
    ]
