# Generated by Django 6.0.1 on 2026-05-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_bono_creditos_restantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='bloque',
            field=models.CharField(choices=[('09:00', '09:00 - 10:30'), ('10:30', '10:30 - 12:00'), ('12:00', '12:00 - 13:30'), ('17:00', '17:00 - 18:30'), ('18:30', '18:30 - 20:00'), ('20:00', '20:00 - 21:30')], max_length=5),
        ),
    ]
