# Generated by Django 6.0.1 on 2026-05-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_reserva_bloque'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('pista', 'fecha', 'bloque'), name='reserva_unica_por_pista_fecha_bloque'),
        ),
    ]
