# Generated by Django 6.0.1 on 2026-05-03 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_reserva_reserva_unica_por_pista_fecha_bloque'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='bono_consumido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reservas.bono'),
        ),
    ]
